[workspace]
resolver = "2"
members = [
		"node",
		"runtime",
		"parachain-runtime",
]

[profile.release]
panic = 'unwind'

[workspace.dependencies]
clap = { version = "4.4.6", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
futures = "0.3.28"
hex-literal = { version = "0.4.1"}
jsonrpsee = { version = "0.16.2", features = ["server"] }
log = { version = "0.4.20", default-features = false }
serde = { version = "1.0.189", features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
smallvec = "1.11.1"
color-print = "0.3.5"

# Substrate
frame-benchmarking = { version = "24.0.0", default-features = false }
frame-benchmarking-cli = { version = "28.0.0" }
frame-executive = { version = "24.0.0", default-features = false }
frame-support = { version = "24.0.0", default-features = false }
frame-system = { version = "24.0.0", default-features = false }
frame-system-benchmarking = { version = "24.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "22.0.0", default-features = false }
frame-try-runtime = { version = "0.30.0", default-features = false }
pallet-aura = { version = "23.0.0", default-features = false }
pallet-authorship = { version = "24.0.0", default-features = false }
pallet-balances = { version = "24.0.0", default-features = false }
pallet-session = { version = "24.0.0", default-features = false }
pallet-sudo = { version = "24.0.0", default-features = false }
pallet-timestamp = { version = "23.0.0", default-features = false }
pallet-transaction-payment = { version = "24.0.0", default-features = false }
pallet-transaction-payment-rpc = { version = "26.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "24.0.0", default-features = false }
sc-basic-authorship = { version = "0.30.0" }
sc-chain-spec = { version = "23.0.0" }
sc-cli = { version = "0.32.0" }
sc-client-api = { version = "24.0.0" }
sc-consensus = { version = "0.29.0" }
sc-executor = { version = "0.28.0" }
sc-network = { version = "0.30.0" }
sc-network-sync = { version = "0.29.0" }
sc-offchain = { version = "25.0.0" }
sc-rpc = { version = "25.0.0" }
sc-service = { version = "0.31.0" }
sc-sysinfo = { version = "23.0.0" }
sc-telemetry = { version = "11.0.0" }
sc-tracing = { version = "24.0.0" }
sc-transaction-pool = { version = "24.0.0" }
sc-transaction-pool-api = { version = "24.0.0" }
sp-api = { version = "22.0.0", default-features = false }
sp-block-builder = { version = "22.0.0", default-features = false }
sp-blockchain = { version = "24.0.0" }
sp-consensus-aura = { version = "0.28.0", default-features = false }
sp-core = { version = "24.0.0", default-features = false }
sp-inherents = { version = "22.0.0", default-features = false }
sp-io = { version = "26.0.0", default-features = false }
sp-keystore = { version = "0.30.0" }
sp-offchain = { version = "22.0.0", default-features = false }
sp-runtime = { version = "27.0.0", default-features = false }
sp-session = { version = "23.0.0", default-features = false }
sp-std = { version = "11.0.0", default-features = false }
sp-timestamp = { version = "22.0.0" }
sp-transaction-pool = { version = "22.0.0", default-features = false }
sp-version = { version = "25.0.0", default-features = false }
substrate-frame-rpc-system = { version = "24.0.0" }
substrate-prometheus-endpoint = { version = "0.15.0" }
substrate-wasm-builder = { version = "13.0.0" }
substrate-build-script-utils = { version = "8.0.0" }
try-runtime-cli = { version = "0.34.0" }

# extra deps for running a solo node on top of a parachain
pallet-grandpa = { version = "24.0.0", default-features = false }
sc-consensus-grandpa = { version = "0.15.0", default-features = false }
sp-consensus-grandpa = { version = "9.0.0", default-features = false }
sp-genesis-builder = { version = "0.3.0", default-features = false }
sp-storage = { version = "16.0.0", default-features = false }
sc-consensus-aura = { version = "0.30.0", default-features = false }
sc-consensus-manual-seal = { version = "0.31.0", default-features = false}

# extra deps for setting up pallet-contracts
pallet-contracts = { version = "23.0.0", default-features = false }
pallet-contracts-primitives = { version = "27.0.0", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "12.0.0", default-features = false }
pallet-assets = { version = "25.0.0", default-features = false }
pallet-utility = { version = "24.0.0", default-features = false }

# Polkadot
pallet-xcm = { version = "3.0.0", default-features = false }
polkadot-cli =  { version = "3.0.0", features = ["rococo-native"] }
polkadot-parachain-primitives = { version = "2.0.0", default-features = false }
polkadot-primitives = { version = "3.0.0" }
polkadot-runtime-common = { version = "3.0.0", default-features = false }
xcm = { package="staging-xcm", version = "3.0.0", default-features = false }
xcm-builder = { package="staging-xcm-builder", version = "3.0.1", default-features = false }
xcm-executor = { package="staging-xcm-executor", version = "3.0.0", default-features = false }

# Cumulus
cumulus-client-cli = { version = "0.3.0" }
cumulus-client-collator = { version = "0.3.0" }
cumulus-client-consensus-proposer = { version = "0.3.0" }
cumulus-client-consensus-aura = { version = "0.3.0" }
cumulus-client-consensus-common = { version = "0.3.0" }
cumulus-client-service = { version = "0.3.0" }
cumulus-pallet-aura-ext = { version = "0.3.0", default-features = false }
cumulus-pallet-dmp-queue = { version = "0.3.0", default-features = false }
cumulus-pallet-parachain-system = { version = "0.3.0", default-features = false, features = ["parameterized-consensus-hook",] }
cumulus-pallet-session-benchmarking = {version = "5.0.0", default-features = false }
cumulus-pallet-xcm = { version = "0.3.0", default-features = false }
cumulus-pallet-xcmp-queue = { version = "0.3.0", default-features = false }
cumulus-primitives-core = { version = "0.3.0", default-features = false }
cumulus-primitives-parachain-inherent = { version = "0.3.0" }
cumulus-primitives-timestamp = { version = "0.3.0", default-features = false }
cumulus-primitives-utility = { version = "0.3.0", default-features = false }
cumulus-relay-chain-interface = { version = "0.3.0" }
pallet-collator-selection = { version = "5.0.0", default-features = false }
parachain-info = { package = "staging-parachain-info", version = "0.3.0", default-features = false }
